version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  install:
    executor: node/default   
    steps:
      - checkout
      - run: npm install
  functional_test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: "Run example tests"
          command: npm run test:headless

workflows:
  all_branch:
    jobs:
      - install
      - functional_test:
          requires:
            - install

