# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  install:
    docker:
      - image: cimg/base:stable    
    steps:
      - checkout
      - run: npm install
  functional_test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Run example tests"
          command: npm run test:headless

workflows:
  feature_branch:
    jobs:
      - install:
          filters:
            branches:
              only: /feature\d+/
      - functional_test:
          requires:
            - install

