version: 2.1

orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.4.0  

jobs:
  install:
    executor: node/default
    working_directory: ~/testcafe-circleCI
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.17'
      - run: node --version
      - node/install-packages:
          app-dir: ~/testcafe-circleCI
          cache-path: node_modules
          override-ci-command: npm i
      - persist_to_workspace:
          root: .
          paths:
            - .          
  functional_test:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - checkout
      - browser-tools/install-chrome
      - run:
          name: Check chrome install      
          command: google-chrome --version
      - run:
          name: "Run example tests"
          command: npm run test:headless

workflows:
  all_branch:
    jobs:
      - install
      - functional_test:
          requires:
            - install

